[WIP] Improve ECS errors outputs
hazelops/ecs-deploy pull request #1
Opened 2021-04-06 14:59 UTC by igorkotof

2021-04-14 06:37 UTC, AutomationD requested changes
Nice work! 
Let's add some ASCICinema to the PR to demo the functionality.

2021-04-14 07:46 UTC, igorkotof commented
> Nice work!
> Let's add some ASCICinema to the PR to demo the functionality.

added testing video

2021-04-19 06:27 UTC, AutomationD approved these changes
Amazing work @igorkotof, thank you!
Minor question about message language.

2021-04-19 06:27 UTC, AutomationD commented on ecs_deploy/cli.py
> +        failure_message += 'Stopped reason of tasks:\n %s\n' % (task_stopped_reason)
Let's update message to something like:
> Stop reason of the task: 

Any objections?

2021-04-20 21:44 UTC, merged